DROP TABLE IF EXISTS visitors;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS moves;
DROP TABLE IF EXISTS dep_schedules;
DROP TABLE IF EXISTS emp_schedules;
DROP TABLE IF EXISTS edits;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS departments;

DROP SEQUENCE IF EXISTS GLOBAL_SEQ;
DROP SEQUENCE IF EXISTS MOVES_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START 10000;
CREATE SEQUENCE MOVES_SEQ START 10000;

CREATE TABLE departments
(
  id    INTEGER PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  name  VARCHAR(255) NOT NULL UNIQUE
);
CREATE UNIQUE INDEX departments_unique_name_idx ON departments (name);

CREATE TABLE positions
(
  id        INTEGER PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  position  VARCHAR(100) NOT NULL UNIQUE
);